# Generated by Django 5.0.6 on 2024-06-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
                ('description_detail', models.TextField(blank=True, max_length=500, null=True, verbose_name='Подробное описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=50, verbose_name='Статус')),
                ('date_completion', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
            ],
            options={
                'verbose_name': 'Cписок задач',
                'verbose_name_plural': 'Списки задач',
                'db_table': 'todo_lists',
            },
        ),
    ]
