# Generated by Django 5.0.6 on 2024-06-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('status', models.CharField(default='new', max_length=50, verbose_name='Статус')),
                ('date_completion', models.DateField(auto_now_add=True, null=True, verbose_name='Дата выполнения')),
            ],
            options={
                'verbose_name': 'Cписок задач',
                'verbose_name_plural': 'Списки задач',
                'db_table': 'todo_lists',
            },
        ),
    ]
